### ISSUE TITLE
How to view the swagger document?

### ISSUE THREAD

**Issue by ayushidalmia** [crowdwave/serve_swagger#2]
Hi Andrew,

Thanks for this repo. However, I was wondering on how to view the swagger documentation in my browser? 

Everything else is working fine :)

**Comment by richardARPANET** [comment]
Slow reply but you can use https://github.com/rdidyk/falcon-swagger-ui to achieve this.

If you edit the bottom of the example `petstore.py` as below it will work:

```python
from falcon_swagger_ui import register_swaggerui_app

api = application = falcon.API()
server = SpecServer(operation_handlers=operation_handlers)
with open('petstore.yml') as f:
    server.load_spec_swagger(f.read())
api.add_sink(server, r'/')

# Setup swagger UI
page_title = 'Falcon Swagger Doc'
favicon_url = 'https://falconframework.org/favicon-32x32.png'
SWAGGERUI_URL = '/swagger'  # without trailing slash
SCHEMA_URL = 'http://petstore.swagger.io/v2/swagger.json'
register_swaggerui_app(
    application, SWAGGERUI_URL, SCHEMA_URL,
    page_title=page_title,
    favicon_url=favicon_url,
    config={'supportedSubmitMethods': ['get'], }
)
```

Then visit http://localhost:8001/swagger/

Note that you'd also want to add a view to serve `SCHEMA_URL` from the same server however.

**Comment by ayushidalmia** [comment]
Thanks @richardARPANET
